GCC = gcc
CFLAGS = -fopenmp -lm

PROGRAMAS = lab01 lab02 lab03 lab04

All: $(PROGRAMAS)

lab01:
	$(GCC) $(CFLAGS) $@.c -o $@ $(CFLAGS)
lab02:
	$(GCC) $(CFLAGS) $@.c -o $@ $(CFLAGS)
lab03:
	$(GCC) $(CFLAGS) $@.c -o $@ $(CFLAGS)
lab04:
	$(GCC) $(CFLAGS) $@.c -o $@ $(CFLAGS)

clean:
	$(RM) $(PROGRAMAS)
